name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Docker image tag to test
        type: string
        default: staging
      compute_instance:
        description: Test compute instances
        type: boolean
        default: true
      managed_postgresql:
        description: Test managed PostgreSQL (~5 min)
        type: boolean
        default: false
      managed_kubernetes:
        description: Test Managed Kubernetes (~15 min)
        type: boolean
        default: false
      network_load_balancer:
        description: Test Network Load Balancers
        type: boolean
        default: false
      managed_kafka:
        description: Test Managed Kafka (~10 min)
        type: boolean
        default: false
      application_load_balancer:
        description: Test Application Load Balancers
        type: boolean
        default: false
      managed_redis:
        description: Test Managed Redis (~5 min)
        type: boolean
        default: false
      managed_clickhouse:
        description: Test Managed ClickHouse (~10 min)
        type: boolean
        default: false
      managed_mysql:
        description: Test Managed MySQL (~5 min)
        type: boolean
        default: false

jobs:
  compute-instance:
    if: ${{ inputs.compute_instance }}
    uses: ./.github/workflows/e2e-compute-instance.yml
    with:
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit

  managed-postgresql:
    if: ${{ inputs.managed_postgresql }}
    uses: ./.github/workflows/e2e-managed-postgresql.yml
    with:
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit

  managed-kubernetes:
    if: ${{ inputs.managed_kubernetes }}
    uses: ./.github/workflows/e2e-managed-kubernetes.yml
    with:
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit

  network-load-balancer:
    if: ${{ inputs.network_load_balancer }}
    uses: ./.github/workflows/e2e-network-load-balancer.yml
    with:
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit

  managed-kafka:
    if: ${{ inputs.managed_kafka }}
    uses: ./.github/workflows/e2e-managed-kafka.yml
    with:
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit

  application-load-balancer:
    if: ${{ inputs.application_load_balancer }}
    uses: ./.github/workflows/e2e-application-load-balancer.yml
    with:
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit

  managed-redis:
    if: ${{ inputs.managed_redis }}
    uses: ./.github/workflows/e2e-managed-redis.yml
    with:
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit

  managed-clickhouse:
    if: ${{ inputs.managed_clickhouse }}
    uses: ./.github/workflows/e2e-managed-clickhouse.yml
    with:
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit

  managed-mysql:
    if: ${{ inputs.managed_mysql }}
    uses: ./.github/workflows/e2e-managed-mysql.yml
    with:
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit
